// Copyright (c) Mysten Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v6.33.0
// source: sui/rpc/v2/balance_change.proto

package suiv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The delta, or change, in balance for an address for a particular `Coin` type.
type BalanceChange struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The account address that is affected by this balance change event.
	Address *string `protobuf:"bytes,1,opt,name=address,proto3,oneof" json:"address,omitempty"`
	// The `Coin` type of this balance change event.
	CoinType *string `protobuf:"bytes,2,opt,name=coin_type,json=coinType,proto3,oneof" json:"coin_type,omitempty"`
	// The amount or change in balance.
	Amount *string `protobuf:"bytes,3,opt,name=amount,proto3,oneof" json:"amount,omitempty"`
}

func (x *BalanceChange) Reset() {
	*x = BalanceChange{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sui_rpc_v2_balance_change_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BalanceChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceChange) ProtoMessage() {}

func (x *BalanceChange) ProtoReflect() protoreflect.Message {
	mi := &file_sui_rpc_v2_balance_change_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceChange.ProtoReflect.Descriptor instead.
func (*BalanceChange) Descriptor() ([]byte, []int) {
	return file_sui_rpc_v2_balance_change_proto_rawDescGZIP(), []int{0}
}

func (x *BalanceChange) GetAddress() string {
	if x != nil && x.Address != nil {
		return *x.Address
	}
	return ""
}

func (x *BalanceChange) GetCoinType() string {
	if x != nil && x.CoinType != nil {
		return *x.CoinType
	}
	return ""
}

func (x *BalanceChange) GetAmount() string {
	if x != nil && x.Amount != nil {
		return *x.Amount
	}
	return ""
}

var File_sui_rpc_v2_balance_change_proto protoreflect.FileDescriptor

var file_sui_rpc_v2_balance_change_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x73, 0x75, 0x69, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x76, 0x32, 0x2f, 0x62, 0x61, 0x6c,
	0x61, 0x6e, 0x63, 0x65, 0x5f, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0a, 0x73, 0x75, 0x69, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x32, 0x22, 0x92, 0x01,
	0x0a, 0x0d, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x12,
	0x1d, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x00, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x88, 0x01, 0x01, 0x12, 0x20,
	0x0a, 0x09, 0x63, 0x6f, 0x69, 0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x48, 0x01, 0x52, 0x08, 0x63, 0x6f, 0x69, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x88, 0x01, 0x01,
	0x12, 0x1b, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x48, 0x02, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x88, 0x01, 0x01, 0x42, 0x0a, 0x0a,
	0x08, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x63, 0x6f,
	0x69, 0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x61, 0x6d, 0x6f, 0x75,
	0x6e, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sui_rpc_v2_balance_change_proto_rawDescOnce sync.Once
	file_sui_rpc_v2_balance_change_proto_rawDescData = file_sui_rpc_v2_balance_change_proto_rawDesc
)

func file_sui_rpc_v2_balance_change_proto_rawDescGZIP() []byte {
	file_sui_rpc_v2_balance_change_proto_rawDescOnce.Do(func() {
		file_sui_rpc_v2_balance_change_proto_rawDescData = protoimpl.X.CompressGZIP(file_sui_rpc_v2_balance_change_proto_rawDescData)
	})
	return file_sui_rpc_v2_balance_change_proto_rawDescData
}

var file_sui_rpc_v2_balance_change_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_sui_rpc_v2_balance_change_proto_goTypes = []interface{}{
	(*BalanceChange)(nil), // 0: sui.rpc.v2.BalanceChange
}
var file_sui_rpc_v2_balance_change_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sui_rpc_v2_balance_change_proto_init() }
func file_sui_rpc_v2_balance_change_proto_init() {
	if File_sui_rpc_v2_balance_change_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sui_rpc_v2_balance_change_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BalanceChange); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_sui_rpc_v2_balance_change_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sui_rpc_v2_balance_change_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sui_rpc_v2_balance_change_proto_goTypes,
		DependencyIndexes: file_sui_rpc_v2_balance_change_proto_depIdxs,
		MessageInfos:      file_sui_rpc_v2_balance_change_proto_msgTypes,
	}.Build()
	File_sui_rpc_v2_balance_change_proto = out.File
	file_sui_rpc_v2_balance_change_proto_rawDesc = nil
	file_sui_rpc_v2_balance_change_proto_goTypes = nil
	file_sui_rpc_v2_balance_change_proto_depIdxs = nil
}
