// Copyright (c) Mysten Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v6.33.0
// source: sui/rpc/v2/filter.proto

package suiv2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DNF filter for transactions: any term may match, and each term is an AND
// of signed literals.
// An absent filter matches everything. A present filter must have at least one
// term.
type TransactionFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Terms are ORed together.
	Terms []*TransactionTerm `protobuf:"bytes,1,rep,name=terms,proto3" json:"terms,omitempty"`
}

func (x *TransactionFilter) Reset() {
	*x = TransactionFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sui_rpc_v2_filter_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransactionFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionFilter) ProtoMessage() {}

func (x *TransactionFilter) ProtoReflect() protoreflect.Message {
	mi := &file_sui_rpc_v2_filter_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionFilter.ProtoReflect.Descriptor instead.
func (*TransactionFilter) Descriptor() ([]byte, []int) {
	return file_sui_rpc_v2_filter_proto_rawDescGZIP(), []int{0}
}

func (x *TransactionFilter) GetTerms() []*TransactionTerm {
	if x != nil {
		return x.Terms
	}
	return nil
}

// One conjunction in a transaction DNF filter.
type TransactionTerm struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Literals are ANDed together.
	Literals []*TransactionLiteral `protobuf:"bytes,1,rep,name=literals,proto3" json:"literals,omitempty"`
}

func (x *TransactionTerm) Reset() {
	*x = TransactionTerm{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sui_rpc_v2_filter_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransactionTerm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionTerm) ProtoMessage() {}

func (x *TransactionTerm) ProtoReflect() protoreflect.Message {
	mi := &file_sui_rpc_v2_filter_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionTerm.ProtoReflect.Descriptor instead.
func (*TransactionTerm) Descriptor() ([]byte, []int) {
	return file_sui_rpc_v2_filter_proto_rawDescGZIP(), []int{1}
}

func (x *TransactionTerm) GetLiterals() []*TransactionLiteral {
	if x != nil {
		return x.Literals
	}
	return nil
}

// One signed transaction predicate literal: a predicate, optionally negated.
type TransactionLiteral struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// When true, the literal matches transactions that the predicate does *not*
	// match.
	Negated bool `protobuf:"varint,1,opt,name=negated,proto3" json:"negated,omitempty"`
	// The transaction-index predicate to match.
	//
	// Types that are assignable to Predicate:
	//
	//	*TransactionLiteral_Sender
	//	*TransactionLiteral_AffectedAddress
	//	*TransactionLiteral_AffectedObject
	//	*TransactionLiteral_MoveCall
	//	*TransactionLiteral_EmitModule
	//	*TransactionLiteral_EventType
	//	*TransactionLiteral_EventStreamHead
	//	*TransactionLiteral_PackageWrite
	Predicate isTransactionLiteral_Predicate `protobuf_oneof:"predicate"`
}

func (x *TransactionLiteral) Reset() {
	*x = TransactionLiteral{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sui_rpc_v2_filter_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransactionLiteral) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionLiteral) ProtoMessage() {}

func (x *TransactionLiteral) ProtoReflect() protoreflect.Message {
	mi := &file_sui_rpc_v2_filter_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionLiteral.ProtoReflect.Descriptor instead.
func (*TransactionLiteral) Descriptor() ([]byte, []int) {
	return file_sui_rpc_v2_filter_proto_rawDescGZIP(), []int{2}
}

func (x *TransactionLiteral) GetNegated() bool {
	if x != nil {
		return x.Negated
	}
	return false
}

func (m *TransactionLiteral) GetPredicate() isTransactionLiteral_Predicate {
	if m != nil {
		return m.Predicate
	}
	return nil
}

func (x *TransactionLiteral) GetSender() *SenderFilter {
	if x, ok := x.GetPredicate().(*TransactionLiteral_Sender); ok {
		return x.Sender
	}
	return nil
}

func (x *TransactionLiteral) GetAffectedAddress() *AffectedAddressFilter {
	if x, ok := x.GetPredicate().(*TransactionLiteral_AffectedAddress); ok {
		return x.AffectedAddress
	}
	return nil
}

func (x *TransactionLiteral) GetAffectedObject() *AffectedObjectFilter {
	if x, ok := x.GetPredicate().(*TransactionLiteral_AffectedObject); ok {
		return x.AffectedObject
	}
	return nil
}

func (x *TransactionLiteral) GetMoveCall() *MoveCallFilter {
	if x, ok := x.GetPredicate().(*TransactionLiteral_MoveCall); ok {
		return x.MoveCall
	}
	return nil
}

func (x *TransactionLiteral) GetEmitModule() *EmitModuleFilter {
	if x, ok := x.GetPredicate().(*TransactionLiteral_EmitModule); ok {
		return x.EmitModule
	}
	return nil
}

func (x *TransactionLiteral) GetEventType() *EventTypeFilter {
	if x, ok := x.GetPredicate().(*TransactionLiteral_EventType); ok {
		return x.EventType
	}
	return nil
}

func (x *TransactionLiteral) GetEventStreamHead() *EventStreamHeadFilter {
	if x, ok := x.GetPredicate().(*TransactionLiteral_EventStreamHead); ok {
		return x.EventStreamHead
	}
	return nil
}

func (x *TransactionLiteral) GetPackageWrite() *PackageWriteFilter {
	if x, ok := x.GetPredicate().(*TransactionLiteral_PackageWrite); ok {
		return x.PackageWrite
	}
	return nil
}

type isTransactionLiteral_Predicate interface {
	isTransactionLiteral_Predicate()
}

type TransactionLiteral_Sender struct {
	// Match transactions sent by the specified address.
	Sender *SenderFilter `protobuf:"bytes,2,opt,name=sender,proto3,oneof"`
}

type TransactionLiteral_AffectedAddress struct {
	// Match transactions where the specified address's state moved as a side
	// effect: it owns an object after the txn, owned an object before the
	// txn that was mutated/transferred away/deleted/wrapped, or its
	// address-balance changed via an accumulator event.
	AffectedAddress *AffectedAddressFilter `protobuf:"bytes,3,opt,name=affected_address,json=affectedAddress,proto3,oneof"`
}

type TransactionLiteral_AffectedObject struct {
	// Match transactions whose effects include a change for the specified
	// object.
	AffectedObject *AffectedObjectFilter `protobuf:"bytes,4,opt,name=affected_object,json=affectedObject,proto3,oneof"`
}

type TransactionLiteral_MoveCall struct {
	// Match transactions that made a Move call matching the specified filter.
	MoveCall *MoveCallFilter `protobuf:"bytes,5,opt,name=move_call,json=moveCall,proto3,oneof"`
}

type TransactionLiteral_EmitModule struct {
	// Match transactions that emitted an event whose package/module fields
	// match the specified filter.
	EmitModule *EmitModuleFilter `protobuf:"bytes,6,opt,name=emit_module,json=emitModule,proto3,oneof"`
}

type TransactionLiteral_EventType struct {
	// Match transactions that emitted an event with a type matching the
	// specified filter.
	EventType *EventTypeFilter `protobuf:"bytes,7,opt,name=event_type,json=eventType,proto3,oneof"`
}

type TransactionLiteral_EventStreamHead struct {
	// Match transactions that wrote to the specified authenticated event
	// stream head.
	EventStreamHead *EventStreamHeadFilter `protobuf:"bytes,8,opt,name=event_stream_head,json=eventStreamHead,proto3,oneof"`
}

type TransactionLiteral_PackageWrite struct {
	// Match transactions that wrote a Move package — a first publish or an
	// upgrade, of any package.
	PackageWrite *PackageWriteFilter `protobuf:"bytes,9,opt,name=package_write,json=packageWrite,proto3,oneof"`
}

func (*TransactionLiteral_Sender) isTransactionLiteral_Predicate() {}

func (*TransactionLiteral_AffectedAddress) isTransactionLiteral_Predicate() {}

func (*TransactionLiteral_AffectedObject) isTransactionLiteral_Predicate() {}

func (*TransactionLiteral_MoveCall) isTransactionLiteral_Predicate() {}

func (*TransactionLiteral_EmitModule) isTransactionLiteral_Predicate() {}

func (*TransactionLiteral_EventType) isTransactionLiteral_Predicate() {}

func (*TransactionLiteral_EventStreamHead) isTransactionLiteral_Predicate() {}

func (*TransactionLiteral_PackageWrite) isTransactionLiteral_Predicate() {}

// DNF filter for events: any term may match, and each term is an AND of
// signed literals. Sender predicates match all events from matching
// transactions; emit-module, event-type, and event-stream-head predicates match
// individual event-space dimensions. An absent filter matches everything. A
// present filter must have at least one term.
type EventFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Terms are ORed together.
	Terms []*EventTerm `protobuf:"bytes,1,rep,name=terms,proto3" json:"terms,omitempty"`
}

func (x *EventFilter) Reset() {
	*x = EventFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sui_rpc_v2_filter_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventFilter) ProtoMessage() {}

func (x *EventFilter) ProtoReflect() protoreflect.Message {
	mi := &file_sui_rpc_v2_filter_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventFilter.ProtoReflect.Descriptor instead.
func (*EventFilter) Descriptor() ([]byte, []int) {
	return file_sui_rpc_v2_filter_proto_rawDescGZIP(), []int{3}
}

func (x *EventFilter) GetTerms() []*EventTerm {
	if x != nil {
		return x.Terms
	}
	return nil
}

// One conjunction in an event DNF filter.
type EventTerm struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Literals are ANDed together.
	Literals []*EventLiteral `protobuf:"bytes,1,rep,name=literals,proto3" json:"literals,omitempty"`
}

func (x *EventTerm) Reset() {
	*x = EventTerm{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sui_rpc_v2_filter_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventTerm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventTerm) ProtoMessage() {}

func (x *EventTerm) ProtoReflect() protoreflect.Message {
	mi := &file_sui_rpc_v2_filter_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventTerm.ProtoReflect.Descriptor instead.
func (*EventTerm) Descriptor() ([]byte, []int) {
	return file_sui_rpc_v2_filter_proto_rawDescGZIP(), []int{4}
}

func (x *EventTerm) GetLiterals() []*EventLiteral {
	if x != nil {
		return x.Literals
	}
	return nil
}

// One signed event predicate literal: a predicate, optionally negated.
type EventLiteral struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// When true, the literal matches events that the predicate does *not* match.
	Negated bool `protobuf:"varint,1,opt,name=negated,proto3" json:"negated,omitempty"`
	// The event-index predicate to match.
	//
	// Types that are assignable to Predicate:
	//
	//	*EventLiteral_Sender
	//	*EventLiteral_EmitModule
	//	*EventLiteral_EventType
	//	*EventLiteral_EventStreamHead
	Predicate isEventLiteral_Predicate `protobuf_oneof:"predicate"`
}

func (x *EventLiteral) Reset() {
	*x = EventLiteral{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sui_rpc_v2_filter_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventLiteral) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventLiteral) ProtoMessage() {}

func (x *EventLiteral) ProtoReflect() protoreflect.Message {
	mi := &file_sui_rpc_v2_filter_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventLiteral.ProtoReflect.Descriptor instead.
func (*EventLiteral) Descriptor() ([]byte, []int) {
	return file_sui_rpc_v2_filter_proto_rawDescGZIP(), []int{5}
}

func (x *EventLiteral) GetNegated() bool {
	if x != nil {
		return x.Negated
	}
	return false
}

func (m *EventLiteral) GetPredicate() isEventLiteral_Predicate {
	if m != nil {
		return m.Predicate
	}
	return nil
}

func (x *EventLiteral) GetSender() *SenderFilter {
	if x, ok := x.GetPredicate().(*EventLiteral_Sender); ok {
		return x.Sender
	}
	return nil
}

func (x *EventLiteral) GetEmitModule() *EmitModuleFilter {
	if x, ok := x.GetPredicate().(*EventLiteral_EmitModule); ok {
		return x.EmitModule
	}
	return nil
}

func (x *EventLiteral) GetEventType() *EventTypeFilter {
	if x, ok := x.GetPredicate().(*EventLiteral_EventType); ok {
		return x.EventType
	}
	return nil
}

func (x *EventLiteral) GetEventStreamHead() *EventStreamHeadFilter {
	if x, ok := x.GetPredicate().(*EventLiteral_EventStreamHead); ok {
		return x.EventStreamHead
	}
	return nil
}

type isEventLiteral_Predicate interface {
	isEventLiteral_Predicate()
}

type EventLiteral_Sender struct {
	// Match events from transactions sent by the specified address.
	Sender *SenderFilter `protobuf:"bytes,2,opt,name=sender,proto3,oneof"`
}

type EventLiteral_EmitModule struct {
	// Match events whose package/module fields match the specified filter.
	EmitModule *EmitModuleFilter `protobuf:"bytes,3,opt,name=emit_module,json=emitModule,proto3,oneof"`
}

type EventLiteral_EventType struct {
	// Match events whose type matches the specified filter.
	EventType *EventTypeFilter `protobuf:"bytes,4,opt,name=event_type,json=eventType,proto3,oneof"`
}

type EventLiteral_EventStreamHead struct {
	// Match events committed to the specified authenticated event stream head.
	EventStreamHead *EventStreamHeadFilter `protobuf:"bytes,5,opt,name=event_stream_head,json=eventStreamHead,proto3,oneof"`
}

func (*EventLiteral_Sender) isEventLiteral_Predicate() {}

func (*EventLiteral_EmitModule) isEventLiteral_Predicate() {}

func (*EventLiteral_EventType) isEventLiteral_Predicate() {}

func (*EventLiteral_EventStreamHead) isEventLiteral_Predicate() {}

// Match by transaction sender address.
type SenderFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The sender address (hex-encoded).
	Address *string `protobuf:"bytes,1,opt,name=address,proto3,oneof" json:"address,omitempty"`
}

func (x *SenderFilter) Reset() {
	*x = SenderFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sui_rpc_v2_filter_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SenderFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SenderFilter) ProtoMessage() {}

func (x *SenderFilter) ProtoReflect() protoreflect.Message {
	mi := &file_sui_rpc_v2_filter_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SenderFilter.ProtoReflect.Descriptor instead.
func (*SenderFilter) Descriptor() ([]byte, []int) {
	return file_sui_rpc_v2_filter_proto_rawDescGZIP(), []int{6}
}

func (x *SenderFilter) GetAddress() string {
	if x != nil && x.Address != nil {
		return *x.Address
	}
	return ""
}

// Match by any address whose state moved as a side effect of the
// transaction: object ownership changes (in either direction), prior
// owners of removed/wrapped objects, and address-balance changes via
// accumulator events.
type AffectedAddressFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The affected address (hex-encoded).
	Address *string `protobuf:"bytes,1,opt,name=address,proto3,oneof" json:"address,omitempty"`
}

func (x *AffectedAddressFilter) Reset() {
	*x = AffectedAddressFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sui_rpc_v2_filter_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AffectedAddressFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AffectedAddressFilter) ProtoMessage() {}

func (x *AffectedAddressFilter) ProtoReflect() protoreflect.Message {
	mi := &file_sui_rpc_v2_filter_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AffectedAddressFilter.ProtoReflect.Descriptor instead.
func (*AffectedAddressFilter) Descriptor() ([]byte, []int) {
	return file_sui_rpc_v2_filter_proto_rawDescGZIP(), []int{7}
}

func (x *AffectedAddressFilter) GetAddress() string {
	if x != nil && x.Address != nil {
		return *x.Address
	}
	return ""
}

// Match by changed object ID.
type AffectedObjectFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The changed object ID (hex-encoded).
	ObjectId *string `protobuf:"bytes,1,opt,name=object_id,json=objectId,proto3,oneof" json:"object_id,omitempty"`
}

func (x *AffectedObjectFilter) Reset() {
	*x = AffectedObjectFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sui_rpc_v2_filter_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AffectedObjectFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AffectedObjectFilter) ProtoMessage() {}

func (x *AffectedObjectFilter) ProtoReflect() protoreflect.Message {
	mi := &file_sui_rpc_v2_filter_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AffectedObjectFilter.ProtoReflect.Descriptor instead.
func (*AffectedObjectFilter) Descriptor() ([]byte, []int) {
	return file_sui_rpc_v2_filter_proto_rawDescGZIP(), []int{8}
}

func (x *AffectedObjectFilter) GetObjectId() string {
	if x != nil && x.ObjectId != nil {
		return *x.ObjectId
	}
	return ""
}

// Match by Move function call, specified as a `::`-delimited Move path.
//
// Specificity levels:
//
//	"0xpkg"                        -> matches any call in the package
//	"0xpkg::module"                -> matches any call in the module
//	"0xpkg::module::function"      -> matches calls to the exact function
type MoveCallFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Required. Move path of the form `package[::module[::function]]`.
	Function *string `protobuf:"bytes,1,opt,name=function,proto3,oneof" json:"function,omitempty"`
}

func (x *MoveCallFilter) Reset() {
	*x = MoveCallFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sui_rpc_v2_filter_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoveCallFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveCallFilter) ProtoMessage() {}

func (x *MoveCallFilter) ProtoReflect() protoreflect.Message {
	mi := &file_sui_rpc_v2_filter_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveCallFilter.ProtoReflect.Descriptor instead.
func (*MoveCallFilter) Descriptor() ([]byte, []int) {
	return file_sui_rpc_v2_filter_proto_rawDescGZIP(), []int{9}
}

func (x *MoveCallFilter) GetFunction() string {
	if x != nil && x.Function != nil {
		return *x.Function
	}
	return ""
}

// Match by an event's package/module fields, specified as a `::`-delimited
// Move path. These identify the top-level Move call that triggered the event.
//
// Specificity levels:
//
//	"0xpkg"               -> matches events with this package_id
//	"0xpkg::module"       -> matches events with this package_id and module
type EmitModuleFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Required. Move path of the form `package[::module]`.
	Module *string `protobuf:"bytes,1,opt,name=module,proto3,oneof" json:"module,omitempty"`
}

func (x *EmitModuleFilter) Reset() {
	*x = EmitModuleFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sui_rpc_v2_filter_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmitModuleFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmitModuleFilter) ProtoMessage() {}

func (x *EmitModuleFilter) ProtoReflect() protoreflect.Message {
	mi := &file_sui_rpc_v2_filter_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmitModuleFilter.ProtoReflect.Descriptor instead.
func (*EmitModuleFilter) Descriptor() ([]byte, []int) {
	return file_sui_rpc_v2_filter_proto_rawDescGZIP(), []int{10}
}

func (x *EmitModuleFilter) GetModule() string {
	if x != nil && x.Module != nil {
		return *x.Module
	}
	return ""
}

// Match by event struct type, specified as a Move type string.
//
// Specificity levels:
//
//	"0xaddr"                              -> matches events whose type is defined at this address
//	"0xaddr::module"                      -> matches events whose type is in this module
//	"0xaddr::module::Name"                -> matches events with this type name (any instantiation)
//	"0xaddr::module::Name<T1, T2>"        -> matches events with this exact generic instantiation
type EventTypeFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Required. Move type string of the form
	// `address[::module[::Name[<type_params>]]]`.
	EventType *string `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3,oneof" json:"event_type,omitempty"`
}

func (x *EventTypeFilter) Reset() {
	*x = EventTypeFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sui_rpc_v2_filter_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventTypeFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventTypeFilter) ProtoMessage() {}

func (x *EventTypeFilter) ProtoReflect() protoreflect.Message {
	mi := &file_sui_rpc_v2_filter_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventTypeFilter.ProtoReflect.Descriptor instead.
func (*EventTypeFilter) Descriptor() ([]byte, []int) {
	return file_sui_rpc_v2_filter_proto_rawDescGZIP(), []int{11}
}

func (x *EventTypeFilter) GetEventType() string {
	if x != nil && x.EventType != nil {
		return *x.EventType
	}
	return ""
}

// Match by authenticated event stream head.
type EventStreamHeadFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The stream id address (hex-encoded).
	StreamId *string `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3,oneof" json:"stream_id,omitempty"`
}

func (x *EventStreamHeadFilter) Reset() {
	*x = EventStreamHeadFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sui_rpc_v2_filter_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EventStreamHeadFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventStreamHeadFilter) ProtoMessage() {}

func (x *EventStreamHeadFilter) ProtoReflect() protoreflect.Message {
	mi := &file_sui_rpc_v2_filter_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventStreamHeadFilter.ProtoReflect.Descriptor instead.
func (*EventStreamHeadFilter) Descriptor() ([]byte, []int) {
	return file_sui_rpc_v2_filter_proto_rawDescGZIP(), []int{12}
}

func (x *EventStreamHeadFilter) GetStreamId() string {
	if x != nil && x.StreamId != nil {
		return *x.StreamId
	}
	return ""
}

// Match transactions that wrote a Move package.
type PackageWriteFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PackageWriteFilter) Reset() {
	*x = PackageWriteFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sui_rpc_v2_filter_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PackageWriteFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackageWriteFilter) ProtoMessage() {}

func (x *PackageWriteFilter) ProtoReflect() protoreflect.Message {
	mi := &file_sui_rpc_v2_filter_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackageWriteFilter.ProtoReflect.Descriptor instead.
func (*PackageWriteFilter) Descriptor() ([]byte, []int) {
	return file_sui_rpc_v2_filter_proto_rawDescGZIP(), []int{13}
}

var File_sui_rpc_v2_filter_proto protoreflect.FileDescriptor

var file_sui_rpc_v2_filter_proto_rawDesc = []byte{
	0x0a, 0x17, 0x73, 0x75, 0x69, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x76, 0x32, 0x2f, 0x66, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x73, 0x75, 0x69, 0x2e, 0x72,
	0x70, 0x63, 0x2e, 0x76, 0x32, 0x22, 0x46, 0x0a, 0x11, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x31, 0x0a, 0x05, 0x74, 0x65,
	0x72, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x73, 0x75, 0x69, 0x2e,
	0x72, 0x70, 0x63, 0x2e, 0x76, 0x32, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x54, 0x65, 0x72, 0x6d, 0x52, 0x05, 0x74, 0x65, 0x72, 0x6d, 0x73, 0x22, 0x4d, 0x0a,
	0x0f, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x65, 0x72, 0x6d,
	0x12, 0x3a, 0x0a, 0x08, 0x6c, 0x69, 0x74, 0x65, 0x72, 0x61, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x73, 0x75, 0x69, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x32, 0x2e,
	0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x74, 0x65, 0x72,
	0x61, 0x6c, 0x52, 0x08, 0x6c, 0x69, 0x74, 0x65, 0x72, 0x61, 0x6c, 0x73, 0x22, 0xde, 0x04, 0x0a,
	0x12, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x74, 0x65,
	0x72, 0x61, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x6e, 0x65, 0x67, 0x61, 0x74, 0x65, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x6e, 0x65, 0x67, 0x61, 0x74, 0x65, 0x64, 0x12, 0x32, 0x0a,
	0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e,
	0x73, 0x75, 0x69, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x32, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x65,
	0x72, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x48, 0x00, 0x52, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65,
	0x72, 0x12, 0x4e, 0x0a, 0x10, 0x61, 0x66, 0x66, 0x65, 0x63, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x73, 0x75,
	0x69, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x32, 0x2e, 0x41, 0x66, 0x66, 0x65, 0x63, 0x74, 0x65,
	0x64, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x48, 0x00,
	0x52, 0x0f, 0x61, 0x66, 0x66, 0x65, 0x63, 0x74, 0x65, 0x64, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x12, 0x4b, 0x0a, 0x0f, 0x61, 0x66, 0x66, 0x65, 0x63, 0x74, 0x65, 0x64, 0x5f, 0x6f, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x73, 0x75, 0x69,
	0x2e, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x32, 0x2e, 0x41, 0x66, 0x66, 0x65, 0x63, 0x74, 0x65, 0x64,
	0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x48, 0x00, 0x52, 0x0e,
	0x61, 0x66, 0x66, 0x65, 0x63, 0x74, 0x65, 0x64, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x39,
	0x0a, 0x09, 0x6d, 0x6f, 0x76, 0x65, 0x5f, 0x63, 0x61, 0x6c, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x73, 0x75, 0x69, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x32, 0x2e, 0x4d,
	0x6f, 0x76, 0x65, 0x43, 0x61, 0x6c, 0x6c, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x48, 0x00, 0x52,
	0x08, 0x6d, 0x6f, 0x76, 0x65, 0x43, 0x61, 0x6c, 0x6c, 0x12, 0x3f, 0x0a, 0x0b, 0x65, 0x6d, 0x69,
	0x74, 0x5f, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c,
	0x2e, 0x73, 0x75, 0x69, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x32, 0x2e, 0x45, 0x6d, 0x69, 0x74,
	0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x48, 0x00, 0x52, 0x0a,
	0x65, 0x6d, 0x69, 0x74, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x12, 0x3c, 0x0a, 0x0a, 0x65, 0x76,
	0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b,
	0x2e, 0x73, 0x75, 0x69, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x32, 0x2e, 0x45, 0x76, 0x65, 0x6e,
	0x74, 0x54, 0x79, 0x70, 0x65, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x48, 0x00, 0x52, 0x09, 0x65,
	0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x4f, 0x0a, 0x11, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x5f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x5f, 0x68, 0x65, 0x61, 0x64, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x73, 0x75, 0x69, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x32,
	0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x48, 0x65, 0x61, 0x64,
	0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x48, 0x00, 0x52, 0x0f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x53,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x48, 0x65, 0x61, 0x64, 0x12, 0x45, 0x0a, 0x0d, 0x70, 0x61, 0x63,
	0x6b, 0x61, 0x67, 0x65, 0x5f, 0x77, 0x72, 0x69, 0x74, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1e, 0x2e, 0x73, 0x75, 0x69, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x32, 0x2e, 0x50, 0x61,
	0x63, 0x6b, 0x61, 0x67, 0x65, 0x57, 0x72, 0x69, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72,
	0x48, 0x00, 0x52, 0x0c, 0x70, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x57, 0x72, 0x69, 0x74, 0x65,
	0x42, 0x0b, 0x0a, 0x09, 0x70, 0x72, 0x65, 0x64, 0x69, 0x63, 0x61, 0x74, 0x65, 0x22, 0x3a, 0x0a,
	0x0b, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x2b, 0x0a, 0x05,
	0x74, 0x65, 0x72, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x73, 0x75,
	0x69, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x32, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x65,
	0x72, 0x6d, 0x52, 0x05, 0x74, 0x65, 0x72, 0x6d, 0x73, 0x22, 0x41, 0x0a, 0x09, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x54, 0x65, 0x72, 0x6d, 0x12, 0x34, 0x0a, 0x08, 0x6c, 0x69, 0x74, 0x65, 0x72, 0x61,
	0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x73, 0x75, 0x69, 0x2e, 0x72,
	0x70, 0x63, 0x2e, 0x76, 0x32, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x74, 0x65, 0x72,
	0x61, 0x6c, 0x52, 0x08, 0x6c, 0x69, 0x74, 0x65, 0x72, 0x61, 0x6c, 0x73, 0x22, 0xb9, 0x02, 0x0a,
	0x0c, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x74, 0x65, 0x72, 0x61, 0x6c, 0x12, 0x18, 0x0a,
	0x07, 0x6e, 0x65, 0x67, 0x61, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x6e, 0x65, 0x67, 0x61, 0x74, 0x65, 0x64, 0x12, 0x32, 0x0a, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x73, 0x75, 0x69, 0x2e, 0x72, 0x70,
	0x63, 0x2e, 0x76, 0x32, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x46, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x48, 0x00, 0x52, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x3f, 0x0a, 0x0b, 0x65,
	0x6d, 0x69, 0x74, 0x5f, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1c, 0x2e, 0x73, 0x75, 0x69, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x32, 0x2e, 0x45, 0x6d,
	0x69, 0x74, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x48, 0x00,
	0x52, 0x0a, 0x65, 0x6d, 0x69, 0x74, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x12, 0x3c, 0x0a, 0x0a,
	0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1b, 0x2e, 0x73, 0x75, 0x69, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x76, 0x32, 0x2e, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x48, 0x00, 0x52,
	0x09, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x4f, 0x0a, 0x11, 0x65, 0x76,
	0x65, 0x6e, 0x74, 0x5f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x5f, 0x68, 0x65, 0x61, 0x64, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x73, 0x75, 0x69, 0x2e, 0x72, 0x70, 0x63, 0x2e,
	0x76, 0x32, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x48, 0x65,
	0x61, 0x64, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x48, 0x00, 0x52, 0x0f, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x48, 0x65, 0x61, 0x64, 0x42, 0x0b, 0x0a, 0x09, 0x70,
	0x72, 0x65, 0x64, 0x69, 0x63, 0x61, 0x74, 0x65, 0x22, 0x39, 0x0a, 0x0c, 0x53, 0x65, 0x6e, 0x64,
	0x65, 0x72, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x1d, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x07, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x88, 0x01, 0x01, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x61, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x22, 0x42, 0x0a, 0x15, 0x41, 0x66, 0x66, 0x65, 0x63, 0x74, 0x65, 0x64, 0x41,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x1d, 0x0a, 0x07,
	0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52,
	0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x88, 0x01, 0x01, 0x42, 0x0a, 0x0a, 0x08, 0x5f,
	0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x46, 0x0a, 0x14, 0x41, 0x66, 0x66, 0x65, 0x63,
	0x74, 0x65, 0x64, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12,
	0x20, 0x0a, 0x09, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x48, 0x00, 0x52, 0x08, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x88, 0x01,
	0x01, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x22,
	0x3e, 0x0a, 0x0e, 0x4d, 0x6f, 0x76, 0x65, 0x43, 0x61, 0x6c, 0x6c, 0x46, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x12, 0x1f, 0x0a, 0x08, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x08, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x88,
	0x01, 0x01, 0x42, 0x0b, 0x0a, 0x09, 0x5f, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22,
	0x3a, 0x0a, 0x10, 0x45, 0x6d, 0x69, 0x74, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x46, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x12, 0x1b, 0x0a, 0x06, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x06, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x88, 0x01, 0x01,
	0x42, 0x09, 0x0a, 0x07, 0x5f, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x22, 0x44, 0x0a, 0x0f, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x22,
	0x0a, 0x0a, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x48, 0x00, 0x52, 0x09, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x88,
	0x01, 0x01, 0x42, 0x0d, 0x0a, 0x0b, 0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70,
	0x65, 0x22, 0x47, 0x0a, 0x15, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x48, 0x65, 0x61, 0x64, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x20, 0x0a, 0x09, 0x73, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52,
	0x08, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x49, 0x64, 0x88, 0x01, 0x01, 0x42, 0x0c, 0x0a, 0x0a,
	0x5f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x5f, 0x69, 0x64, 0x22, 0x14, 0x0a, 0x12, 0x50, 0x61,
	0x63, 0x6b, 0x61, 0x67, 0x65, 0x57, 0x72, 0x69, 0x74, 0x65, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sui_rpc_v2_filter_proto_rawDescOnce sync.Once
	file_sui_rpc_v2_filter_proto_rawDescData = file_sui_rpc_v2_filter_proto_rawDesc
)

func file_sui_rpc_v2_filter_proto_rawDescGZIP() []byte {
	file_sui_rpc_v2_filter_proto_rawDescOnce.Do(func() {
		file_sui_rpc_v2_filter_proto_rawDescData = protoimpl.X.CompressGZIP(file_sui_rpc_v2_filter_proto_rawDescData)
	})
	return file_sui_rpc_v2_filter_proto_rawDescData
}

var file_sui_rpc_v2_filter_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_sui_rpc_v2_filter_proto_goTypes = []interface{}{
	(*TransactionFilter)(nil),     // 0: sui.rpc.v2.TransactionFilter
	(*TransactionTerm)(nil),       // 1: sui.rpc.v2.TransactionTerm
	(*TransactionLiteral)(nil),    // 2: sui.rpc.v2.TransactionLiteral
	(*EventFilter)(nil),           // 3: sui.rpc.v2.EventFilter
	(*EventTerm)(nil),             // 4: sui.rpc.v2.EventTerm
	(*EventLiteral)(nil),          // 5: sui.rpc.v2.EventLiteral
	(*SenderFilter)(nil),          // 6: sui.rpc.v2.SenderFilter
	(*AffectedAddressFilter)(nil), // 7: sui.rpc.v2.AffectedAddressFilter
	(*AffectedObjectFilter)(nil),  // 8: sui.rpc.v2.AffectedObjectFilter
	(*MoveCallFilter)(nil),        // 9: sui.rpc.v2.MoveCallFilter
	(*EmitModuleFilter)(nil),      // 10: sui.rpc.v2.EmitModuleFilter
	(*EventTypeFilter)(nil),       // 11: sui.rpc.v2.EventTypeFilter
	(*EventStreamHeadFilter)(nil), // 12: sui.rpc.v2.EventStreamHeadFilter
	(*PackageWriteFilter)(nil),    // 13: sui.rpc.v2.PackageWriteFilter
}
var file_sui_rpc_v2_filter_proto_depIdxs = []int32{
	1,  // 0: sui.rpc.v2.TransactionFilter.terms:type_name -> sui.rpc.v2.TransactionTerm
	2,  // 1: sui.rpc.v2.TransactionTerm.literals:type_name -> sui.rpc.v2.TransactionLiteral
	6,  // 2: sui.rpc.v2.TransactionLiteral.sender:type_name -> sui.rpc.v2.SenderFilter
	7,  // 3: sui.rpc.v2.TransactionLiteral.affected_address:type_name -> sui.rpc.v2.AffectedAddressFilter
	8,  // 4: sui.rpc.v2.TransactionLiteral.affected_object:type_name -> sui.rpc.v2.AffectedObjectFilter
	9,  // 5: sui.rpc.v2.TransactionLiteral.move_call:type_name -> sui.rpc.v2.MoveCallFilter
	10, // 6: sui.rpc.v2.TransactionLiteral.emit_module:type_name -> sui.rpc.v2.EmitModuleFilter
	11, // 7: sui.rpc.v2.TransactionLiteral.event_type:type_name -> sui.rpc.v2.EventTypeFilter
	12, // 8: sui.rpc.v2.TransactionLiteral.event_stream_head:type_name -> sui.rpc.v2.EventStreamHeadFilter
	13, // 9: sui.rpc.v2.TransactionLiteral.package_write:type_name -> sui.rpc.v2.PackageWriteFilter
	4,  // 10: sui.rpc.v2.EventFilter.terms:type_name -> sui.rpc.v2.EventTerm
	5,  // 11: sui.rpc.v2.EventTerm.literals:type_name -> sui.rpc.v2.EventLiteral
	6,  // 12: sui.rpc.v2.EventLiteral.sender:type_name -> sui.rpc.v2.SenderFilter
	10, // 13: sui.rpc.v2.EventLiteral.emit_module:type_name -> sui.rpc.v2.EmitModuleFilter
	11, // 14: sui.rpc.v2.EventLiteral.event_type:type_name -> sui.rpc.v2.EventTypeFilter
	12, // 15: sui.rpc.v2.EventLiteral.event_stream_head:type_name -> sui.rpc.v2.EventStreamHeadFilter
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_sui_rpc_v2_filter_proto_init() }
func file_sui_rpc_v2_filter_proto_init() {
	if File_sui_rpc_v2_filter_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sui_rpc_v2_filter_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransactionFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sui_rpc_v2_filter_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransactionTerm); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sui_rpc_v2_filter_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransactionLiteral); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sui_rpc_v2_filter_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sui_rpc_v2_filter_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventTerm); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sui_rpc_v2_filter_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventLiteral); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sui_rpc_v2_filter_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SenderFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sui_rpc_v2_filter_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AffectedAddressFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sui_rpc_v2_filter_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AffectedObjectFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sui_rpc_v2_filter_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoveCallFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sui_rpc_v2_filter_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmitModuleFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sui_rpc_v2_filter_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventTypeFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sui_rpc_v2_filter_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EventStreamHeadFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sui_rpc_v2_filter_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PackageWriteFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_sui_rpc_v2_filter_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*TransactionLiteral_Sender)(nil),
		(*TransactionLiteral_AffectedAddress)(nil),
		(*TransactionLiteral_AffectedObject)(nil),
		(*TransactionLiteral_MoveCall)(nil),
		(*TransactionLiteral_EmitModule)(nil),
		(*TransactionLiteral_EventType)(nil),
		(*TransactionLiteral_EventStreamHead)(nil),
		(*TransactionLiteral_PackageWrite)(nil),
	}
	file_sui_rpc_v2_filter_proto_msgTypes[5].OneofWrappers = []interface{}{
		(*EventLiteral_Sender)(nil),
		(*EventLiteral_EmitModule)(nil),
		(*EventLiteral_EventType)(nil),
		(*EventLiteral_EventStreamHead)(nil),
	}
	file_sui_rpc_v2_filter_proto_msgTypes[6].OneofWrappers = []interface{}{}
	file_sui_rpc_v2_filter_proto_msgTypes[7].OneofWrappers = []interface{}{}
	file_sui_rpc_v2_filter_proto_msgTypes[8].OneofWrappers = []interface{}{}
	file_sui_rpc_v2_filter_proto_msgTypes[9].OneofWrappers = []interface{}{}
	file_sui_rpc_v2_filter_proto_msgTypes[10].OneofWrappers = []interface{}{}
	file_sui_rpc_v2_filter_proto_msgTypes[11].OneofWrappers = []interface{}{}
	file_sui_rpc_v2_filter_proto_msgTypes[12].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sui_rpc_v2_filter_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sui_rpc_v2_filter_proto_goTypes,
		DependencyIndexes: file_sui_rpc_v2_filter_proto_depIdxs,
		MessageInfos:      file_sui_rpc_v2_filter_proto_msgTypes,
	}.Build()
	File_sui_rpc_v2_filter_proto = out.File
	file_sui_rpc_v2_filter_proto_rawDesc = nil
	file_sui_rpc_v2_filter_proto_goTypes = nil
	file_sui_rpc_v2_filter_proto_depIdxs = nil
}
