// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package suiv2

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// LedgerServiceClient is the client API for LedgerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LedgerServiceClient interface {
	// Query the service for general information about its current state.
	GetServiceInfo(ctx context.Context, in *GetServiceInfoRequest, opts ...grpc.CallOption) (*GetServiceInfoResponse, error)
	GetObject(ctx context.Context, in *GetObjectRequest, opts ...grpc.CallOption) (*GetObjectResponse, error)
	BatchGetObjects(ctx context.Context, in *BatchGetObjectsRequest, opts ...grpc.CallOption) (*BatchGetObjectsResponse, error)
	GetTransaction(ctx context.Context, in *GetTransactionRequest, opts ...grpc.CallOption) (*GetTransactionResponse, error)
	BatchGetTransactions(ctx context.Context, in *BatchGetTransactionsRequest, opts ...grpc.CallOption) (*BatchGetTransactionsResponse, error)
	GetCheckpoint(ctx context.Context, in *GetCheckpointRequest, opts ...grpc.CallOption) (*GetCheckpointResponse, error)
	GetEpoch(ctx context.Context, in *GetEpochRequest, opts ...grpc.CallOption) (*GetEpochResponse, error)
	// List checkpoints matching the provided filters.
	//
	// Checkpoints are returned in ascending or descending checkpoint sequence
	// number order according to the query options ordering.
	// A checkpoint matches if any transaction it contains satisfies the filter.
	ListCheckpoints(ctx context.Context, in *ListCheckpointsRequest, opts ...grpc.CallOption) (LedgerService_ListCheckpointsClient, error)
	// List transactions matching the provided filters.
	//
	// Transactions are returned in ascending or descending transaction sequence
	// order according to the query options ordering.
	ListTransactions(ctx context.Context, in *ListTransactionsRequest, opts ...grpc.CallOption) (LedgerService_ListTransactionsClient, error)
	// List events matching the provided filters.
	//
	// Events are returned in ascending or descending packed event sequence order
	// according to the query options ordering.
	ListEvents(ctx context.Context, in *ListEventsRequest, opts ...grpc.CallOption) (LedgerService_ListEventsClient, error)
}

type ledgerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLedgerServiceClient(cc grpc.ClientConnInterface) LedgerServiceClient {
	return &ledgerServiceClient{cc}
}

func (c *ledgerServiceClient) GetServiceInfo(ctx context.Context, in *GetServiceInfoRequest, opts ...grpc.CallOption) (*GetServiceInfoResponse, error) {
	out := new(GetServiceInfoResponse)
	err := c.cc.Invoke(ctx, "/sui.rpc.v2.LedgerService/GetServiceInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerServiceClient) GetObject(ctx context.Context, in *GetObjectRequest, opts ...grpc.CallOption) (*GetObjectResponse, error) {
	out := new(GetObjectResponse)
	err := c.cc.Invoke(ctx, "/sui.rpc.v2.LedgerService/GetObject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerServiceClient) BatchGetObjects(ctx context.Context, in *BatchGetObjectsRequest, opts ...grpc.CallOption) (*BatchGetObjectsResponse, error) {
	out := new(BatchGetObjectsResponse)
	err := c.cc.Invoke(ctx, "/sui.rpc.v2.LedgerService/BatchGetObjects", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerServiceClient) GetTransaction(ctx context.Context, in *GetTransactionRequest, opts ...grpc.CallOption) (*GetTransactionResponse, error) {
	out := new(GetTransactionResponse)
	err := c.cc.Invoke(ctx, "/sui.rpc.v2.LedgerService/GetTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerServiceClient) BatchGetTransactions(ctx context.Context, in *BatchGetTransactionsRequest, opts ...grpc.CallOption) (*BatchGetTransactionsResponse, error) {
	out := new(BatchGetTransactionsResponse)
	err := c.cc.Invoke(ctx, "/sui.rpc.v2.LedgerService/BatchGetTransactions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerServiceClient) GetCheckpoint(ctx context.Context, in *GetCheckpointRequest, opts ...grpc.CallOption) (*GetCheckpointResponse, error) {
	out := new(GetCheckpointResponse)
	err := c.cc.Invoke(ctx, "/sui.rpc.v2.LedgerService/GetCheckpoint", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerServiceClient) GetEpoch(ctx context.Context, in *GetEpochRequest, opts ...grpc.CallOption) (*GetEpochResponse, error) {
	out := new(GetEpochResponse)
	err := c.cc.Invoke(ctx, "/sui.rpc.v2.LedgerService/GetEpoch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerServiceClient) ListCheckpoints(ctx context.Context, in *ListCheckpointsRequest, opts ...grpc.CallOption) (LedgerService_ListCheckpointsClient, error) {
	stream, err := c.cc.NewStream(ctx, &LedgerService_ServiceDesc.Streams[0], "/sui.rpc.v2.LedgerService/ListCheckpoints", opts...)
	if err != nil {
		return nil, err
	}
	x := &ledgerServiceListCheckpointsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type LedgerService_ListCheckpointsClient interface {
	Recv() (*ListCheckpointsResponse, error)
	grpc.ClientStream
}

type ledgerServiceListCheckpointsClient struct {
	grpc.ClientStream
}

func (x *ledgerServiceListCheckpointsClient) Recv() (*ListCheckpointsResponse, error) {
	m := new(ListCheckpointsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *ledgerServiceClient) ListTransactions(ctx context.Context, in *ListTransactionsRequest, opts ...grpc.CallOption) (LedgerService_ListTransactionsClient, error) {
	stream, err := c.cc.NewStream(ctx, &LedgerService_ServiceDesc.Streams[1], "/sui.rpc.v2.LedgerService/ListTransactions", opts...)
	if err != nil {
		return nil, err
	}
	x := &ledgerServiceListTransactionsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type LedgerService_ListTransactionsClient interface {
	Recv() (*ListTransactionsResponse, error)
	grpc.ClientStream
}

type ledgerServiceListTransactionsClient struct {
	grpc.ClientStream
}

func (x *ledgerServiceListTransactionsClient) Recv() (*ListTransactionsResponse, error) {
	m := new(ListTransactionsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *ledgerServiceClient) ListEvents(ctx context.Context, in *ListEventsRequest, opts ...grpc.CallOption) (LedgerService_ListEventsClient, error) {
	stream, err := c.cc.NewStream(ctx, &LedgerService_ServiceDesc.Streams[2], "/sui.rpc.v2.LedgerService/ListEvents", opts...)
	if err != nil {
		return nil, err
	}
	x := &ledgerServiceListEventsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type LedgerService_ListEventsClient interface {
	Recv() (*ListEventsResponse, error)
	grpc.ClientStream
}

type ledgerServiceListEventsClient struct {
	grpc.ClientStream
}

func (x *ledgerServiceListEventsClient) Recv() (*ListEventsResponse, error) {
	m := new(ListEventsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// LedgerServiceServer is the server API for LedgerService service.
// All implementations must embed UnimplementedLedgerServiceServer
// for forward compatibility
type LedgerServiceServer interface {
	// Query the service for general information about its current state.
	GetServiceInfo(context.Context, *GetServiceInfoRequest) (*GetServiceInfoResponse, error)
	GetObject(context.Context, *GetObjectRequest) (*GetObjectResponse, error)
	BatchGetObjects(context.Context, *BatchGetObjectsRequest) (*BatchGetObjectsResponse, error)
	GetTransaction(context.Context, *GetTransactionRequest) (*GetTransactionResponse, error)
	BatchGetTransactions(context.Context, *BatchGetTransactionsRequest) (*BatchGetTransactionsResponse, error)
	GetCheckpoint(context.Context, *GetCheckpointRequest) (*GetCheckpointResponse, error)
	GetEpoch(context.Context, *GetEpochRequest) (*GetEpochResponse, error)
	// List checkpoints matching the provided filters.
	//
	// Checkpoints are returned in ascending or descending checkpoint sequence
	// number order according to the query options ordering.
	// A checkpoint matches if any transaction it contains satisfies the filter.
	ListCheckpoints(*ListCheckpointsRequest, LedgerService_ListCheckpointsServer) error
	// List transactions matching the provided filters.
	//
	// Transactions are returned in ascending or descending transaction sequence
	// order according to the query options ordering.
	ListTransactions(*ListTransactionsRequest, LedgerService_ListTransactionsServer) error
	// List events matching the provided filters.
	//
	// Events are returned in ascending or descending packed event sequence order
	// according to the query options ordering.
	ListEvents(*ListEventsRequest, LedgerService_ListEventsServer) error
	mustEmbedUnimplementedLedgerServiceServer()
}

// UnimplementedLedgerServiceServer must be embedded to have forward compatible implementations.
type UnimplementedLedgerServiceServer struct {
}

func (UnimplementedLedgerServiceServer) GetServiceInfo(context.Context, *GetServiceInfoRequest) (*GetServiceInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetServiceInfo not implemented")
}
func (UnimplementedLedgerServiceServer) GetObject(context.Context, *GetObjectRequest) (*GetObjectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetObject not implemented")
}
func (UnimplementedLedgerServiceServer) BatchGetObjects(context.Context, *BatchGetObjectsRequest) (*BatchGetObjectsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchGetObjects not implemented")
}
func (UnimplementedLedgerServiceServer) GetTransaction(context.Context, *GetTransactionRequest) (*GetTransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTransaction not implemented")
}
func (UnimplementedLedgerServiceServer) BatchGetTransactions(context.Context, *BatchGetTransactionsRequest) (*BatchGetTransactionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchGetTransactions not implemented")
}
func (UnimplementedLedgerServiceServer) GetCheckpoint(context.Context, *GetCheckpointRequest) (*GetCheckpointResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCheckpoint not implemented")
}
func (UnimplementedLedgerServiceServer) GetEpoch(context.Context, *GetEpochRequest) (*GetEpochResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEpoch not implemented")
}
func (UnimplementedLedgerServiceServer) ListCheckpoints(*ListCheckpointsRequest, LedgerService_ListCheckpointsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListCheckpoints not implemented")
}
func (UnimplementedLedgerServiceServer) ListTransactions(*ListTransactionsRequest, LedgerService_ListTransactionsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListTransactions not implemented")
}
func (UnimplementedLedgerServiceServer) ListEvents(*ListEventsRequest, LedgerService_ListEventsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListEvents not implemented")
}
func (UnimplementedLedgerServiceServer) mustEmbedUnimplementedLedgerServiceServer() {}

// UnsafeLedgerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LedgerServiceServer will
// result in compilation errors.
type UnsafeLedgerServiceServer interface {
	mustEmbedUnimplementedLedgerServiceServer()
}

func RegisterLedgerServiceServer(s grpc.ServiceRegistrar, srv LedgerServiceServer) {
	s.RegisterService(&LedgerService_ServiceDesc, srv)
}

func _LedgerService_GetServiceInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServiceInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).GetServiceInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sui.rpc.v2.LedgerService/GetServiceInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).GetServiceInfo(ctx, req.(*GetServiceInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerService_GetObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).GetObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sui.rpc.v2.LedgerService/GetObject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).GetObject(ctx, req.(*GetObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerService_BatchGetObjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchGetObjectsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).BatchGetObjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sui.rpc.v2.LedgerService/BatchGetObjects",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).BatchGetObjects(ctx, req.(*BatchGetObjectsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerService_GetTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).GetTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sui.rpc.v2.LedgerService/GetTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).GetTransaction(ctx, req.(*GetTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerService_BatchGetTransactions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchGetTransactionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).BatchGetTransactions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sui.rpc.v2.LedgerService/BatchGetTransactions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).BatchGetTransactions(ctx, req.(*BatchGetTransactionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerService_GetCheckpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCheckpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).GetCheckpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sui.rpc.v2.LedgerService/GetCheckpoint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).GetCheckpoint(ctx, req.(*GetCheckpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerService_GetEpoch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEpochRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).GetEpoch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sui.rpc.v2.LedgerService/GetEpoch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).GetEpoch(ctx, req.(*GetEpochRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerService_ListCheckpoints_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListCheckpointsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LedgerServiceServer).ListCheckpoints(m, &ledgerServiceListCheckpointsServer{stream})
}

type LedgerService_ListCheckpointsServer interface {
	Send(*ListCheckpointsResponse) error
	grpc.ServerStream
}

type ledgerServiceListCheckpointsServer struct {
	grpc.ServerStream
}

func (x *ledgerServiceListCheckpointsServer) Send(m *ListCheckpointsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _LedgerService_ListTransactions_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListTransactionsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LedgerServiceServer).ListTransactions(m, &ledgerServiceListTransactionsServer{stream})
}

type LedgerService_ListTransactionsServer interface {
	Send(*ListTransactionsResponse) error
	grpc.ServerStream
}

type ledgerServiceListTransactionsServer struct {
	grpc.ServerStream
}

func (x *ledgerServiceListTransactionsServer) Send(m *ListTransactionsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _LedgerService_ListEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LedgerServiceServer).ListEvents(m, &ledgerServiceListEventsServer{stream})
}

type LedgerService_ListEventsServer interface {
	Send(*ListEventsResponse) error
	grpc.ServerStream
}

type ledgerServiceListEventsServer struct {
	grpc.ServerStream
}

func (x *ledgerServiceListEventsServer) Send(m *ListEventsResponse) error {
	return x.ServerStream.SendMsg(m)
}

// LedgerService_ServiceDesc is the grpc.ServiceDesc for LedgerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LedgerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sui.rpc.v2.LedgerService",
	HandlerType: (*LedgerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetServiceInfo",
			Handler:    _LedgerService_GetServiceInfo_Handler,
		},
		{
			MethodName: "GetObject",
			Handler:    _LedgerService_GetObject_Handler,
		},
		{
			MethodName: "BatchGetObjects",
			Handler:    _LedgerService_BatchGetObjects_Handler,
		},
		{
			MethodName: "GetTransaction",
			Handler:    _LedgerService_GetTransaction_Handler,
		},
		{
			MethodName: "BatchGetTransactions",
			Handler:    _LedgerService_BatchGetTransactions_Handler,
		},
		{
			MethodName: "GetCheckpoint",
			Handler:    _LedgerService_GetCheckpoint_Handler,
		},
		{
			MethodName: "GetEpoch",
			Handler:    _LedgerService_GetEpoch_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListCheckpoints",
			Handler:       _LedgerService_ListCheckpoints_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ListTransactions",
			Handler:       _LedgerService_ListTransactions_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ListEvents",
			Handler:       _LedgerService_ListEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "sui/rpc/v2/ledger_service.proto",
}
