// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package suiv2

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// NameServiceClient is the client API for NameService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NameServiceClient interface {
	LookupName(ctx context.Context, in *LookupNameRequest, opts ...grpc.CallOption) (*LookupNameResponse, error)
	ReverseLookupName(ctx context.Context, in *ReverseLookupNameRequest, opts ...grpc.CallOption) (*ReverseLookupNameResponse, error)
}

type nameServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNameServiceClient(cc grpc.ClientConnInterface) NameServiceClient {
	return &nameServiceClient{cc}
}

func (c *nameServiceClient) LookupName(ctx context.Context, in *LookupNameRequest, opts ...grpc.CallOption) (*LookupNameResponse, error) {
	out := new(LookupNameResponse)
	err := c.cc.Invoke(ctx, "/sui.rpc.v2.NameService/LookupName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nameServiceClient) ReverseLookupName(ctx context.Context, in *ReverseLookupNameRequest, opts ...grpc.CallOption) (*ReverseLookupNameResponse, error) {
	out := new(ReverseLookupNameResponse)
	err := c.cc.Invoke(ctx, "/sui.rpc.v2.NameService/ReverseLookupName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NameServiceServer is the server API for NameService service.
// All implementations must embed UnimplementedNameServiceServer
// for forward compatibility
type NameServiceServer interface {
	LookupName(context.Context, *LookupNameRequest) (*LookupNameResponse, error)
	ReverseLookupName(context.Context, *ReverseLookupNameRequest) (*ReverseLookupNameResponse, error)
	mustEmbedUnimplementedNameServiceServer()
}

// UnimplementedNameServiceServer must be embedded to have forward compatible implementations.
type UnimplementedNameServiceServer struct {
}

func (UnimplementedNameServiceServer) LookupName(context.Context, *LookupNameRequest) (*LookupNameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LookupName not implemented")
}
func (UnimplementedNameServiceServer) ReverseLookupName(context.Context, *ReverseLookupNameRequest) (*ReverseLookupNameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReverseLookupName not implemented")
}
func (UnimplementedNameServiceServer) mustEmbedUnimplementedNameServiceServer() {}

// UnsafeNameServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NameServiceServer will
// result in compilation errors.
type UnsafeNameServiceServer interface {
	mustEmbedUnimplementedNameServiceServer()
}

func RegisterNameServiceServer(s grpc.ServiceRegistrar, srv NameServiceServer) {
	s.RegisterService(&NameService_ServiceDesc, srv)
}

func _NameService_LookupName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LookupNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NameServiceServer).LookupName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sui.rpc.v2.NameService/LookupName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NameServiceServer).LookupName(ctx, req.(*LookupNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NameService_ReverseLookupName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReverseLookupNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NameServiceServer).ReverseLookupName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sui.rpc.v2.NameService/ReverseLookupName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NameServiceServer).ReverseLookupName(ctx, req.(*ReverseLookupNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NameService_ServiceDesc is the grpc.ServiceDesc for NameService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NameService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sui.rpc.v2.NameService",
	HandlerType: (*NameServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "LookupName",
			Handler:    _NameService_LookupName_Handler,
		},
		{
			MethodName: "ReverseLookupName",
			Handler:    _NameService_ReverseLookupName_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sui/rpc/v2/name_service.proto",
}
