// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package suiv2

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SubscriptionServiceClient is the client API for SubscriptionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SubscriptionServiceClient interface {
	// Subscribe to the stream of checkpoints.
	//
	// The stream begins at the latest executed checkpoint as seen by the
	// server and yields checkpoints matching the filter as they are executed.
	// A checkpoint matches if any transaction it contains satisfies the
	// filter.
	SubscribeCheckpoints(ctx context.Context, in *SubscribeCheckpointsRequest, opts ...grpc.CallOption) (SubscriptionService_SubscribeCheckpointsClient, error)
	// Subscribe to the stream of transactions.
	//
	// The stream begins at the latest executed checkpoint as seen by the
	// server and yields transactions matching the filter as they are executed.
	SubscribeTransactions(ctx context.Context, in *SubscribeTransactionsRequest, opts ...grpc.CallOption) (SubscriptionService_SubscribeTransactionsClient, error)
	// Subscribe to the stream of events.
	//
	// The stream begins at the latest executed checkpoint as seen by the
	// server and yields events matching the filter as they are emitted.
	SubscribeEvents(ctx context.Context, in *SubscribeEventsRequest, opts ...grpc.CallOption) (SubscriptionService_SubscribeEventsClient, error)
}

type subscriptionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSubscriptionServiceClient(cc grpc.ClientConnInterface) SubscriptionServiceClient {
	return &subscriptionServiceClient{cc}
}

func (c *subscriptionServiceClient) SubscribeCheckpoints(ctx context.Context, in *SubscribeCheckpointsRequest, opts ...grpc.CallOption) (SubscriptionService_SubscribeCheckpointsClient, error) {
	stream, err := c.cc.NewStream(ctx, &SubscriptionService_ServiceDesc.Streams[0], "/sui.rpc.v2.SubscriptionService/SubscribeCheckpoints", opts...)
	if err != nil {
		return nil, err
	}
	x := &subscriptionServiceSubscribeCheckpointsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SubscriptionService_SubscribeCheckpointsClient interface {
	Recv() (*SubscribeCheckpointsResponse, error)
	grpc.ClientStream
}

type subscriptionServiceSubscribeCheckpointsClient struct {
	grpc.ClientStream
}

func (x *subscriptionServiceSubscribeCheckpointsClient) Recv() (*SubscribeCheckpointsResponse, error) {
	m := new(SubscribeCheckpointsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *subscriptionServiceClient) SubscribeTransactions(ctx context.Context, in *SubscribeTransactionsRequest, opts ...grpc.CallOption) (SubscriptionService_SubscribeTransactionsClient, error) {
	stream, err := c.cc.NewStream(ctx, &SubscriptionService_ServiceDesc.Streams[1], "/sui.rpc.v2.SubscriptionService/SubscribeTransactions", opts...)
	if err != nil {
		return nil, err
	}
	x := &subscriptionServiceSubscribeTransactionsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SubscriptionService_SubscribeTransactionsClient interface {
	Recv() (*SubscribeTransactionsResponse, error)
	grpc.ClientStream
}

type subscriptionServiceSubscribeTransactionsClient struct {
	grpc.ClientStream
}

func (x *subscriptionServiceSubscribeTransactionsClient) Recv() (*SubscribeTransactionsResponse, error) {
	m := new(SubscribeTransactionsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *subscriptionServiceClient) SubscribeEvents(ctx context.Context, in *SubscribeEventsRequest, opts ...grpc.CallOption) (SubscriptionService_SubscribeEventsClient, error) {
	stream, err := c.cc.NewStream(ctx, &SubscriptionService_ServiceDesc.Streams[2], "/sui.rpc.v2.SubscriptionService/SubscribeEvents", opts...)
	if err != nil {
		return nil, err
	}
	x := &subscriptionServiceSubscribeEventsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SubscriptionService_SubscribeEventsClient interface {
	Recv() (*SubscribeEventsResponse, error)
	grpc.ClientStream
}

type subscriptionServiceSubscribeEventsClient struct {
	grpc.ClientStream
}

func (x *subscriptionServiceSubscribeEventsClient) Recv() (*SubscribeEventsResponse, error) {
	m := new(SubscribeEventsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SubscriptionServiceServer is the server API for SubscriptionService service.
// All implementations must embed UnimplementedSubscriptionServiceServer
// for forward compatibility
type SubscriptionServiceServer interface {
	// Subscribe to the stream of checkpoints.
	//
	// The stream begins at the latest executed checkpoint as seen by the
	// server and yields checkpoints matching the filter as they are executed.
	// A checkpoint matches if any transaction it contains satisfies the
	// filter.
	SubscribeCheckpoints(*SubscribeCheckpointsRequest, SubscriptionService_SubscribeCheckpointsServer) error
	// Subscribe to the stream of transactions.
	//
	// The stream begins at the latest executed checkpoint as seen by the
	// server and yields transactions matching the filter as they are executed.
	SubscribeTransactions(*SubscribeTransactionsRequest, SubscriptionService_SubscribeTransactionsServer) error
	// Subscribe to the stream of events.
	//
	// The stream begins at the latest executed checkpoint as seen by the
	// server and yields events matching the filter as they are emitted.
	SubscribeEvents(*SubscribeEventsRequest, SubscriptionService_SubscribeEventsServer) error
	mustEmbedUnimplementedSubscriptionServiceServer()
}

// UnimplementedSubscriptionServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSubscriptionServiceServer struct {
}

func (UnimplementedSubscriptionServiceServer) SubscribeCheckpoints(*SubscribeCheckpointsRequest, SubscriptionService_SubscribeCheckpointsServer) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeCheckpoints not implemented")
}
func (UnimplementedSubscriptionServiceServer) SubscribeTransactions(*SubscribeTransactionsRequest, SubscriptionService_SubscribeTransactionsServer) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeTransactions not implemented")
}
func (UnimplementedSubscriptionServiceServer) SubscribeEvents(*SubscribeEventsRequest, SubscriptionService_SubscribeEventsServer) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeEvents not implemented")
}
func (UnimplementedSubscriptionServiceServer) mustEmbedUnimplementedSubscriptionServiceServer() {}

// UnsafeSubscriptionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SubscriptionServiceServer will
// result in compilation errors.
type UnsafeSubscriptionServiceServer interface {
	mustEmbedUnimplementedSubscriptionServiceServer()
}

func RegisterSubscriptionServiceServer(s grpc.ServiceRegistrar, srv SubscriptionServiceServer) {
	s.RegisterService(&SubscriptionService_ServiceDesc, srv)
}

func _SubscriptionService_SubscribeCheckpoints_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeCheckpointsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SubscriptionServiceServer).SubscribeCheckpoints(m, &subscriptionServiceSubscribeCheckpointsServer{stream})
}

type SubscriptionService_SubscribeCheckpointsServer interface {
	Send(*SubscribeCheckpointsResponse) error
	grpc.ServerStream
}

type subscriptionServiceSubscribeCheckpointsServer struct {
	grpc.ServerStream
}

func (x *subscriptionServiceSubscribeCheckpointsServer) Send(m *SubscribeCheckpointsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _SubscriptionService_SubscribeTransactions_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeTransactionsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SubscriptionServiceServer).SubscribeTransactions(m, &subscriptionServiceSubscribeTransactionsServer{stream})
}

type SubscriptionService_SubscribeTransactionsServer interface {
	Send(*SubscribeTransactionsResponse) error
	grpc.ServerStream
}

type subscriptionServiceSubscribeTransactionsServer struct {
	grpc.ServerStream
}

func (x *subscriptionServiceSubscribeTransactionsServer) Send(m *SubscribeTransactionsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _SubscriptionService_SubscribeEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SubscriptionServiceServer).SubscribeEvents(m, &subscriptionServiceSubscribeEventsServer{stream})
}

type SubscriptionService_SubscribeEventsServer interface {
	Send(*SubscribeEventsResponse) error
	grpc.ServerStream
}

type subscriptionServiceSubscribeEventsServer struct {
	grpc.ServerStream
}

func (x *subscriptionServiceSubscribeEventsServer) Send(m *SubscribeEventsResponse) error {
	return x.ServerStream.SendMsg(m)
}

// SubscriptionService_ServiceDesc is the grpc.ServiceDesc for SubscriptionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SubscriptionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sui.rpc.v2.SubscriptionService",
	HandlerType: (*SubscriptionServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeCheckpoints",
			Handler:       _SubscriptionService_SubscribeCheckpoints_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubscribeTransactions",
			Handler:       _SubscriptionService_SubscribeTransactions_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubscribeEvents",
			Handler:       _SubscriptionService_SubscribeEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "sui/rpc/v2/subscription_service.proto",
}
