// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package suiv2

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TransactionExecutionServiceClient is the client API for TransactionExecutionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TransactionExecutionServiceClient interface {
	ExecuteTransaction(ctx context.Context, in *ExecuteTransactionRequest, opts ...grpc.CallOption) (*ExecuteTransactionResponse, error)
	SimulateTransaction(ctx context.Context, in *SimulateTransactionRequest, opts ...grpc.CallOption) (*SimulateTransactionResponse, error)
}

type transactionExecutionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTransactionExecutionServiceClient(cc grpc.ClientConnInterface) TransactionExecutionServiceClient {
	return &transactionExecutionServiceClient{cc}
}

func (c *transactionExecutionServiceClient) ExecuteTransaction(ctx context.Context, in *ExecuteTransactionRequest, opts ...grpc.CallOption) (*ExecuteTransactionResponse, error) {
	out := new(ExecuteTransactionResponse)
	err := c.cc.Invoke(ctx, "/sui.rpc.v2.TransactionExecutionService/ExecuteTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionExecutionServiceClient) SimulateTransaction(ctx context.Context, in *SimulateTransactionRequest, opts ...grpc.CallOption) (*SimulateTransactionResponse, error) {
	out := new(SimulateTransactionResponse)
	err := c.cc.Invoke(ctx, "/sui.rpc.v2.TransactionExecutionService/SimulateTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TransactionExecutionServiceServer is the server API for TransactionExecutionService service.
// All implementations must embed UnimplementedTransactionExecutionServiceServer
// for forward compatibility
type TransactionExecutionServiceServer interface {
	ExecuteTransaction(context.Context, *ExecuteTransactionRequest) (*ExecuteTransactionResponse, error)
	SimulateTransaction(context.Context, *SimulateTransactionRequest) (*SimulateTransactionResponse, error)
	mustEmbedUnimplementedTransactionExecutionServiceServer()
}

// UnimplementedTransactionExecutionServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTransactionExecutionServiceServer struct {
}

func (UnimplementedTransactionExecutionServiceServer) ExecuteTransaction(context.Context, *ExecuteTransactionRequest) (*ExecuteTransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteTransaction not implemented")
}
func (UnimplementedTransactionExecutionServiceServer) SimulateTransaction(context.Context, *SimulateTransactionRequest) (*SimulateTransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SimulateTransaction not implemented")
}
func (UnimplementedTransactionExecutionServiceServer) mustEmbedUnimplementedTransactionExecutionServiceServer() {
}

// UnsafeTransactionExecutionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TransactionExecutionServiceServer will
// result in compilation errors.
type UnsafeTransactionExecutionServiceServer interface {
	mustEmbedUnimplementedTransactionExecutionServiceServer()
}

func RegisterTransactionExecutionServiceServer(s grpc.ServiceRegistrar, srv TransactionExecutionServiceServer) {
	s.RegisterService(&TransactionExecutionService_ServiceDesc, srv)
}

func _TransactionExecutionService_ExecuteTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionExecutionServiceServer).ExecuteTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sui.rpc.v2.TransactionExecutionService/ExecuteTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionExecutionServiceServer).ExecuteTransaction(ctx, req.(*ExecuteTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionExecutionService_SimulateTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SimulateTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionExecutionServiceServer).SimulateTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sui.rpc.v2.TransactionExecutionService/SimulateTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionExecutionServiceServer).SimulateTransaction(ctx, req.(*SimulateTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TransactionExecutionService_ServiceDesc is the grpc.ServiceDesc for TransactionExecutionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TransactionExecutionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sui.rpc.v2.TransactionExecutionService",
	HandlerType: (*TransactionExecutionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecuteTransaction",
			Handler:    _TransactionExecutionService_ExecuteTransaction_Handler,
		},
		{
			MethodName: "SimulateTransaction",
			Handler:    _TransactionExecutionService_SimulateTransaction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sui/rpc/v2/transaction_execution_service.proto",
}
